project:
  type: website

format:
  html:
    theme: zephyr

website:
  title: "AlienTech"
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    title: "AlienTech"
    pinned: true
    logo: logo.png
    background: primary
    search: true
    right:
      - icon: github
        href: https://github.com/Tomiarry/Alien.github.io
  back-to-top-navigation: true
  page-footer: 
    left: "Copyright 2025, Tomiarry" 
    right: 
      - icon: github
        href: https://github.com/Tomiarry/Alien.github.io
metadata-files: [nbdev.yml]